### ISSUE TITLE
[Bug] Error after a few attempts at guessing the number

### ISSUE THREAD

**Issue by mellobacon** [lucasstarsz/Slope-ECS#7]
**Describe the bug**
I get an error after a few attempts at guessing the number.

**To Reproduce**
1. Run GuessGameExample
2. Attempt to guess the number
3. After a few tries the error will appear

**Expected behavior**
It should continue until there are no numbers left.

**Screenshots**
![image](https://user-images.githubusercontent.com/42365887/108114066-efa88400-705d-11eb-8d8b-6951e97f3cda.png)

**Comment by lucasstarsz** [comment]
This bug has been fixed in [this commit](https://github.com/lucasstarsz/Slope-ECS/commit/803d822db1d281f312dddf63ebe6d8b99fd28029).
Awaiting push to main before closing.
